Added Container Creation as part of the Compile Script

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -29,21 +29,39 @@ generateBuildNumber $SERVICE
 echo "Build the $SERVICE Microservice : mvn -e package"
 echo "---------------------------------------------------------------------------------------"
 mvn -e package
+mvnCompRV=$?
 # -------------------------------------------------------------------------------------------
-#echo cp target/*service*.?ar lib/
-echo "---------------------------------------------------------------------------------------"
-cp target/*service*-spring-boot.jar src/docker/$CONTAINER-spring-boot.jar
-cp target/*service*?.?.?.jar src/docker/$CONTAINER-thin.jar
-cp target/libs/* src/docker/libs/
-echo "Copy the Property File to the Docker Directory (src/docker)"
-cp src/main/resources/application.properties src/docker/
-cp src/main/resources/application.properties .
-echo "---------------------------------------------------------------------------------------"
-# -------------------------------------------------------------------------------------------
-# - Build Docker Images (this can be done thru maven also)
-# -------------------------------------------------------------------------------------------
-echo "$SERVICE Microservice Build Process Complete .............. "
-echo "---------------------------------------------------------------------------------------"
-echo "Start the Service using ./run script and then test it with ./test script"
-echo "After the Successful build and Startup of the Service, It should show the Build No. & Date"
-echo "---------------------------------------------------------------------------------------"
+if [ $mvnCompRV == 0 ] 
+then
+	echo "---------------------------------------------------------------------------------------"
+	echo "Compiling Service > $SERVICE :: SUCCESS"
+	echo "---------------------------------------------------------------------------------------"
+	echo "Copy the Fat and Thin jar files and the libs to the Docker Directory (src/docker)"
+	cp target/*service*-spring-boot.jar src/docker/$CONTAINER-spring-boot.jar
+	cp target/*service*?.?.?.jar src/docker/$CONTAINER-thin.jar
+	cp target/libs/* src/docker/libs/
+	echo "Copy the application.properties File to the Docker Directory (src/docker)"
+	cp src/main/resources/application.properties src/docker/
+	cp src/main/resources/application.properties .
+	echo "---------------------------------------------------------------------------------------"
+	echo "Building the Cocntainer for $SERVICE Service ..... "
+	echo "---------------------------------------------------------------------------------------"
+	cd src/docker
+	build
+	echo "---------------------------------------------------------------------------------------"
+	echo "$SERVICE Microservice Build Process Completed Successfully! ........... "
+	echo "---------------------------------------------------------------------------------------"
+	echo "Start the Service using "
+	echo "  run (Run the SpringBoot App)  OR"
+	echo "  cd src/docker"
+	echo "  start (Start the Container)"
+	echo "Then to test it with"
+	echo "  test (To Test the SpringBoot App)"
+	echo "---------------------------------------------------------------------------------------"
+	echo "After the Successful build and Startup of the Service, It should show the Build No. & Date"
+	echo "---------------------------------------------------------------------------------------"
+else
+	echo "---------------------------------------------------------------------------------------"
+	echo "Compiling Service > $SERVICE :: FAILED!!!"
+	echo "---------------------------------------------------------------------------------------"
+fi
